#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [ -r ~/.profile ]; then
	source ~/.profile
fi

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#
if (( $+commands[nvim] )); then
	export EDITOR='nvim'
	export VISUAL='nvim'
else
	export EDITOR='vim'
	export VISUAL='vim'
fi
export PAGER='less'
export BROWSER='firefox'

#
# Term
#

if [[ "$TERM" != "linux" ]]; then
	#if infocmp "screen-256color-it" > /dev/null 2>&1; then
	#	export TERM="screen-256color-it"
	#	alias ssh="TERM=screen-256color ssh"
	#else
		#export TERM="tmux-256color"
	#fi
fi
#[[ "$TERM" != "linux" ]] && export TERM="xterm-256color"
# Cursor shape and color
[[ "$TERM" != "linux" ]] && printf "\e]12;grey\x7\e[1 q"
[[ "$TERM" == "linux" ]] && source ~/.zprezto/modules/tty-colors/init.zsh
[[ "$TERM" == "linux" && -f /usr/share/consolefonts/ter-d22n.psf.gz ]] && setfont /usr/share/consolefonts/ter-d22n.psf.gz

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='fr_FR.UTF-8@euro'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
# Prevent waiting when pressing <Esc> key
typeset KEYTIMEOUT=1

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  ~/.cabal/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESSCHARSET='utf-8'
#export LESS='-F -g -i -M -R -w -X -z-4 -r'
export LESS='-F -g -i -M -R -w -X -z-4'
# Disable sgr escape sequences
export GROFF_NO_SGR=1

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[lesspipe.sh] )); then
	export LESSOPEN="| /usr/bin/env $commands[lesspipe.sh] %s 2>&-"
elif (( $#commands[lesspipe] )); then
	export LESSOPEN="| /usr/bin/env $commands[lesspipe] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

# vim:ft=zsh
