#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export PATH="$HOME/.linuxbrew/bin:$HOME/.local/bin:$PATH"
export MANPATH="$HOME/.local/share/man:$HOME/.local/man:/usr/local/man:/usr/local/share/man:/usr/share/man"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Additional submodules
[ -f ~/.zprezto/modules/zaw/zaw.zsh ] && source ~/.zprezto/modules/zaw/zaw.zsh
[ -f ~/.zprezto/modules/opp/opp.zsh ] && source ~/.zprezto/modules/opp/opp.zsh
[ -f ~/.zprezto/modules/opp/opp.zsh ] && source ~/.zprezto/modules/opp/opp/*.zsh
[ -f ~/.zprezto/modules/fzf.zsh ] && source ~/.zprezto/modules/fzf.zsh

bindkey "OA" history-search-backward
bindkey "OB" history-search-forward
bindkey "[A" history-search-backward
bindkey "[B" history-search-forward

# ls colors
[ -f ~/.zprezto/modules/dircolors-solarized/dircolors.256dark ] && eval $(dircolors ~/.zprezto/modules/dircolors-solarized/dircolors.256dark)

# GDBmgr vim plugin
export LD_LIBRARY_PATH="$HOME/.vim/bundle/gdbmgr/gdbmgr/src:/usr/local/lib:default"
