#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export PATH="$HOME/.linuxbrew/bin:$HOME/.local/bin:$PATH"
export MANPATH="$HOME/.local/share/man:$HOME/.local/man:/usr/local/man:/usr/local/share/man:/usr/share/man"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Additional submodules
[ -f ~/.zprezto/modules/zaw/zaw.zsh ] && source ~/.zprezto/modules/zaw/zaw.zsh
[ -f ~/.zprezto/modules/opp/opp.zsh ] && source ~/.zprezto/modules/opp/opp.zsh
[ -f ~/.zprezto/modules/opp/opp.zsh ] && source ~/.zprezto/modules/opp/opp/*.zsh
[ -f ~/.zprezto/modules/fzf.zsh ] && source ~/.zprezto/modules/fzf.zsh
[ -f ~/.zprezto/modules/k/k.sh ] && source ~/.zprezto/modules/k/k.sh

bindkey "OA" history-search-backward
bindkey "OB" history-search-forward
bindkey "[A" history-search-backward
bindkey "[B" history-search-forward

giveAFuck() {
	BUFFER="fuck"
	zle accept-line
}

zle -N giveAFuck
bindkey "" "giveAFuck"

# GDBmgr vim plugin
export LD_LIBRARY_PATH="$HOME/.local/lib:/usr/local/lib:$HOME/.vim/bundle/gdbmgr/gdbmgr/src:default"
