#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.zaw/zaw.zsh
source ~/.opp/opp.zsh
source ~/.opp/opp/*.zsh

bindkey "OA" history-search-backward
bindkey "OB" history-search-forward
bindkey "[A" history-search-backward
bindkey "[B" history-search-forward
